SLAP_TEMPLATES = (
    "{user2}വിനെ {user1} ഭിത്തിയിൽ ചേർത്ത് നിർത്തി കണ്ണിൽ മുളക് തേച്ചു😵.",
    "{user2} എന്ന ആളുടെ വായിൽ {user1} തുപ്പി ഇട്ടു.😳",
    "{user2} എന്ന ആളെ കൊണ്ട് {user1} ഓലേക്കപുണ്ണാക്ക് തീറ്റിച്ചു.🤢",
    "{user2} എന്ന ആളെ മുതല കുളത്തിൽ തള്ളി ഇട്ടു",
    "{user2}ക്ക് സയനൈഡ് കൊടുത്തു",
    "{user2} എന്ന ആളെ തീയിൽ ഇട്ടു.",
    "{user2} എന്ന ആൾ {user1} ആയിട്ടു അടി കൂടിയപ്പോ കരിഞ്ഞു പോയി.",
    "{user2} തലയിൽ ഇടി വെട്ടി",
    "{user2} എന്ന ആളുടെ വായിൽ {user1} ഉപ്പിട്ടു.",
    "{user2} എന്ന ആളെ നാട്ടുകാർ തല്ലി കൊന്നു",
    "{user2} പട്ടിണി കിടന്നു മരിച്ചുപോയി",
    "{user2} ജീവിച്ചിരിപ്പുണ്ടോ ഇതൊക്കെ",
    "{user2} എന്ന ആളെ {user1} പേടിപ്പിച്ചു കൊന്നു.",
    "{user2} എന്ന ആൾ വല്യ വിറ്റാണ് കേട്ടോ....",
    "{user2} താനൊസ് സ്നാപ്പ് ചെയ്തപ്പോ മഞ്ഞു പോയി",
    "{user2} എന്ന ആളുടെ കാലിന്റെ ഇടയിൽ ബോംബ് ഇട്ടു പൊട്ടിച്ചു.",
    "{user2} എന്ന ആളുടെ വായിൽ സൂപ്പർ ഗ്ലു ഇട്ടു....",
    "{user2} നെ ലോകത്തിൽ ഏറ്റവും വലിയ ദുരന്തങ്ങൾ ആയിട്ടു പ്രഖ്യാപിച്ചു.",
    "{user2} ക്യാഷ് അങ്ങോട്ടു കൊടുത് വിറ്റു",
    "{user2} ന് {user1} പിണ്ണാക്ക് വാങ്ങി കൊടുത്തു.",
    "{user2}ന്റെ തലയിൽ {user1} ചെണ്ട കൊട്ടി.",
    "{user2}ന്റെ പ്രധാന ഭാഗത്ത്‌ പാൻ വെച്ചടിച്ചു",
    "{user2} ഒരു വികൃത ശരീരം ഉള്ള സോമ്പി ആണ് എനിക് ഒന്നും ചെയ്യാൻ പറ്റില്ല.",
    "{user2} ഒരു മണ്ടൻ ആയതു കൊണ്ട് വെറുതെ വിട്ടിരിക്കുന്നു.",
    "{user2} ന്റെ തലയിൽ ഇഷ്ടിക തള്ളി ഇട്ടു.",
    "{user2} ഒരു കാറ്റത് പറന്നു പോയി.",
    "{user2} ഒരു ബോംബ് എടുത്ത് തിന്നു",
    "{user2} നടന്നു പോയപ്പോൾ കാക്കക്ക് തലയിൽ അപ്പി ഇടാൻ അവസരം കൊടുത്തു",
    "{user2} was terminated by {user1}.",
    "{user2} ഇരുന്നപ്പോൾ കൊന്നു കളഞ്ഞു.",
    "{user2} എന്ന ആളുടെ കണ്ണിൽ പെൻസിൽ എടുത്ത് കുത്തി.",
    "{user2} ന്റെ  ഫോൺ എടുത്ത് വെള്ളത്തിൽ ഇട്ടു.",
    "{user1} എന്ന ആളുടെ ദേഹത്തു കൂടെ {user2} റോഡ് റോളർ കേറ്റി ഇറക്കി.",
    "{user2} ഒരു കല്ലെടുത്ത് മുകളിലോട്ടു എറിഞ്ഞു അത് വന്നു സ്വന്തം തലയിൽ വീണു മരിച്ചു പോയി",
    "{user1} ആരും അറിയാതെ {user2}ന്റെ കാലിൽ ടൈം ബോംബ് വെച്ചു കെട്ടി.",
    "{user1} ഒരു കല്ലെടുത്ത് {user2} എന്ന ആളുടെ മർമ്മം നോക്കി എറിഞ്ഞു.",
    "{user1} put {user2} in check-mate.",
    "{user1} കോടാലി എടുത്ത് {user2} വിന്റെ വായിൽ തിരുകി വെച്ചു.",
    "{user1} {user2}നെ വാരികുഴിയിൽ തള്ളി ഇട്ടു.",
    "{user1} മീൻ ചട്ടി എടുത്ത {user2} ന്റെ തലക്കടിച്ചു",
    "{user2} തുണി ഇല്ലാതെ റോഡിൽ കൂടി ഓടി.",
    "{user2} ന്റെ ഫോണിൽ നിന്നും {user1} പ്രധാന പെട്ട ഫയൽ എല്ലാം തന്നെ ഡിലീറ്റ് ചെയ്തു.",
    "{user1}  {user2}ന്റെ പല്ലെല്ലാം അടിച്ചു താഴെ ഇട്ടു.",
    "{user2} എന്ന ആളുടെ പാന്റ് നാടു റോഡിൽ വെച്ചു ഊരി പോയി.",
    "{user1} അലക്കാത്ത തുണി എടുത്ത് {user2}ന്റെ വായിൽ കുത്തി കേറ്റി.",
    "{user2} കൂടുതൽ തൊള്ള തുറന്നാൽ അടിച്ചു അണ്ണാക്കിൽ തരും എന്നു പറയാൻ പറഞ്ഞു {user1}.",
    "{user2} എന്ന ആളുടെ ബുദ്ധി, ശൂന്യം ആണ്.",
    "{user2} was a mistake. - '{user1}' ",
    "{user1} checkmated {user2} in two moves.",
    "{user2} പെട്രോൾ കുടിച്ചു ചിരിച്ചു",
    "{user1} {user2}നെ ബാറ്റ് വെച്ച് {hits}.",
    "{user1} {user2}നെ കൊക്കയിൽ ഇട്ടു.",
    "{user1} {user2} എന്ന ആളെ പലക എടുത്ത് {hits}",    
    "{user1} {user2} എന്ന ആളുടെ തലയിൽ {hits}.",
    "{user1} {user2} എന്ന ആളുടെ വായിൽ ലാവാ ഒഴിച്ചു.",
    "{user1} വലിയ ഒരു പാറ എടുത്ത് {user2} തലയിൽ ഇട്ടു .",
    "{user1} {user2}ന്റെ തലയിൽ വലിയ പാൻ കാക്ക എടുത്ത് {hits}!.",
    "*{user2} എന്ന ആളെ തല കീഴായി തൂക്കി ഇട്ട് അടിച്ചു*.",
    "*{user2} എന്ന ആളുടെ പിന്നാമ്പുറത്ത് ചട്ടുകം വെച്ചു പൊള്ളിച്ചു*.",
    "*{user2} നെ ഉന്തി ഇട്ടു*.",
    "*{user2} നെ {user1} തല്ലിയിട്ടു ഓടി*.",
    "*{user2} ചെരുപ്പ് ഇട്ടു നടന്നതിന് നാട്ടുകാർ ഓടിച്ചിട്ടു അടിച്ചു*.",
    "{User2}  ഒരു ചുഴലിക്കാറ്റിൽ പെട്ടു പോയി",
    "{User1} പാത്രം എടുത്ത {user2} {throws}"
)

GIFS = [
    "CgACAgQAAx0CSVUvGgAC7KpfWxMrgGyQs-GUUJgt-TSO8cOIDgACaAgAAlZD0VHT3Zynpr5nGxsE",
    "CgACAgUAAx0CU_rCTAABAjdgX1s4NVaeCls6YaH3p43vgdCRwQIAAqsAA4P_MFUYQhyoR-kgpRsE",
    "CgACAgUAAx0CU_rCTAABAjdSX1s3fq5iEJ64YeQLKI8cD7CSuSEAAlUBAAJu09hW5iqWB0hTPD4bBA",
]

SLAP_MASHA_TEMPLATES = (
    "Slap me one more time and I'll mute you.",
    "Stop slapping me. REEEEEEEEEEEEEE.",
    [
        "I am muting you for a minute.",  # normal reply
        "Stop slapping me just because I can't mute you. REEEEEEEEEE.",  # reply to admin
        "tmute",  # command
        "Shut up!",
        "Silence!",
    ],
)

RUN_STRINGS = (
    "{user2} was killed by magic.",
    "{user2} starved without pats.",
    "{user2} was knocked into the void by {user1}.",
    "{user2} fainted.",
    "{user2} is out of usable Pokemon! {user2} whited out!.",
    "{user2} is out of usable Pokemon! {user2} blacked out!.",
    "{user2} got rekt.",
    "{user2}'s melon was split by {user1}.",
    "{user2} was sliced and diced by {user1}.",
    "{user2} played hot-potato with a grenade.",
    "{user2} was knifed by {user1}.",
    "{user2} ate a grenade.",
    "{user2} is what's for dinner!",
    "{user2} was terminated by {user1}.",
    "{user1} spammed {user2}'s email.",
    "{user1} RSA-encrypted {user2} and deleted the private key.",
    "{user1} put {user2} in the friendzone.",
    "{user1} slaps {user2} with a DMCA takedown request!",
    "{user2} got a house call from Doctor {user1}.",
    "{user1} beheaded {user2}.",
    "{user2} got stoned...by an angry mob.",
    "{user1} sued the pants off {user2}.",
    "{user2} was one-hit KO'd by {user1}.",
    "{user1} sent {user2} down the memory hole.",
    "{user2} was a mistake. - '{user1}' ",
    "{user2} was made redundant.",
    "{user1} {hits} {user2} with a bat!.",
    "{user1} {hits} {user2} with a Taijutsu Kick!.",
    "{user1} {hits} {user2} with X-Gloves!.",
    "{user1} {hits} {user2} with a Jet Punch!.",
    "{user1} {hits} {user2} with a Jet Pistol!.",
    "{user1} {hits} {user2} with a United States of Smash!.",
    "{user1} {hits} {user2} with a Detroit Smash!.",
    "{user1} {hits} {user2} with a Texas Smash!.",
    "{user1} {hits} {user2} with a California Smash!.",
    "{user1} {hits} {user2} with a New Hampshire Smash!.",
    "{user1} {hits} {user2} with a Missouri Smash!.",
    "{user1} {hits} {user2} with a Carolina Smash!.",
    "{user1} {hits} {user2} with a King Kong Gun!.",
    "{user1} {hits} {user2} with a baseball bat - metal one.!.",
    "*Serious punches {user2}*.",
    "*Normal punches {user2}*.",
    "*Consecutive Normal punches {user2}*.",
    "*Two Handed Consecutive Normal Punches {user2}*.",
    "*Ignores {user2} to let them die of embarassment*.",
    "*points at {user2}* What's with this sassy... lost child?.",
    "*Hits {user2} with a Fire Tornado*.",
    "{user1} pokes {user2} in the eye !",
    "{user1} pokes {user2} on the sides!",
    "{user1} pokes {user2}!",
    "{user1} pokes {user2} with a needle!",
    "{user1} pokes {user2} with a pen!",
    "{user1} pokes {user2} with a stun gun!",
    "{user2} is secretly a Furry!",
    "Hey Everybody! {user1} is asking me to be mean!",
    "( ･_･)ﾉ⌒●~* (･.･;) <-{user2}",
    "Take this {user2}\n(ﾉﾟДﾟ)ﾉ ))))●~* ",
    "Here {user2} hold this\n(｀・ω・)つ ●~＊",
    "( ・_・)ノΞ●~*  {user2}\nDieeeee!!.",
    "( ・∀・)ｒ鹵~<≪巛;ﾟДﾟ)ﾉ\n*Bug sprays {user2}*.",
    "( ﾟДﾟ)ﾉ占~<巛巛巛.\n-{user2} You pest!",
    "( う-´)づ︻╦̵̵̿╤── \(˚☐˚”)/ {user2}.",
    "{user1} {hits} {user2} with a {item}.",
    "{user1} {hits} {user2} in the face with a {item}.",
    "{user1} {hits} {user2} around a bit with a {item}.",
    "{user1} {throws} a {item} at {user2}.",
    "{user1} grabs a {item} and {throws} it at {user2}'s face.",
    "{user1} launches a {item} in {user2}'s general direction.",
    "{user1} starts slapping {user2} silly with a {item}.",
    "{user1} pins {user2} down and repeatedly {hits} them with a {item}.",
    "{user1} grabs up a {item} and {hits} {user2} with it.",
    "{user1} ties {user2} to a chair and {throws} a {item} at them.",
    "{user1} gave a friendly push to help {user2} learn to swim in lava.",
    "{user1} bullied {user2}.",
    "Nyaan ate {user2}'s leg. *nomnomnom*",
    "{user1} {throws} a master ball at {user2}, resistance is futile.",
    "{user1} hits {user2} with an action beam...bbbbbb (ง・ω・)ง ====*",
    "{user1} ara ara's {user2}.",
    "{user1} ora ora's {user2}.",
    "{user1} muda muda's {user2}.",
    "{user2} was turned into a Jojo reference!",
    "{user1} hits {user2} with {item}.",
    "Round 2!..Ready? .. FIGHT!!",
    "WhoPixel will oof {user2} to infinity and beyond.",
    "{user2} ate a bat and discovered a new disease.",
    "{user1} folded {user2} into a paper plane",
    "{user1} served {user2} some bat soup.",
    "{user2} was sent to his home, the planet of the apes.",
    "{user1} kicked {user2} out of a moving train.",
    "{user2} just killed John Wick’s dog.",
    "{user1} performed an Avada Kedavra spell on {user2}.",
    "{user1} subjected {user2} to a fiery furnace.",
    "Sakura Haruno just got more useful than {user2}",
    "{user1} unplugged {user2}'s life support.",
    "{user1} subscribed {user2}' to 5 years of bad internet.",
    "You know what’s worse than Dad jokes? {user2}!",
    "{user1} took all of {user2}'s cookies.",
    "{user2} wa mou.......Shindeiru! - {user1}.",
    "{user2} lost his race piece!",  # No game no life reference
    "Shut up {user2}, you are just {user2}.",  # No game no life reference
    "{user1} hits {user2} with Aka si anse!",  # No game no life reference
    "@NeoTheKitty scratches {user2}",  # Pixels pet cat - @NeoTheKitty
    "Majin buu ate {user2}",  # Dbz
    "Goblin slayer slays {user2}",  # Goblin Slayer
)

PAT_TEMPLATES = (
    "{user1} pats {user2} on the head.",
    "*gently rubs {user2}'s head*.",
    "*{user1} mofumofus {user2}'s head*",
    "*{user1} messes up {user2}'s head*",
    "*{user1} intensly rubs {user2}'s head*",
    "*{user2}'s waifu pats their head*",
    "*{user2}'s got free headpats*",
    "No pats for {user2}!",
    "Oh no! We are all out of pats.",
    "This is a designated no pat zone!",
    "No pats for {user2}!",
    "{user1} spoils {user2} with headpats!",
    "{user2} received one free headpat!",
    "{user1} headpats {user2} whilst giving a lap pillow",
    "{user1} aggressively pats {user2}",
    "{user1} gently strokes {user2}'s head",
    "Pat, pat, pat, pat",
    "{user2} could not escape {user1}'s headpats",
    "{user2}.exe has stopped working",
    "{user1} rubs {user2} on the neck",
    "Must... extort... HEADPATS",
    "{user1} headpats {user2}'s head with a pat",
    "{user1} pats {user2} unexpectedly",
    "{user1} pats {user2} with consent, maybe?",
    "Pat pat, {user2} honto kawaii ne!",
    "{user1} headpats {user2} at 420apm",
    "{user1} bellyrubs {user2}",
    "{user1} pats {user2} friendlily",
    "{user2} uses HEADPATS? O KAWAII KOTO",
    "*headpats.gif intensifies for {user2}*",
    "(*´ω´(*｀ω｀)",
    "(ｏ・_・)ノ”(ᴗ_ ᴗ。)",
    "(*￣▽￣)ノ”(- -*)",
    "(っ´ω`)ﾉ(╥ω╥)",
    "( ´Д｀)ﾉ(´･ω･`) ﾅﾃﾞﾅﾃﾞ",
)

PAT_GIFS = (
    "CgACAgQAAxkBAALRX19Xs7tBdOH1gQwS_rglVRkTbgVYAAKEAgACmQn9UWlyGa_xy9_aGwQ",
    "CgACAgEAAxkBAALRYF9Xs8EnhsDfDpld3ILoqTbzDmwxAAJFAAOJxjlHECanwn69E5QbBA",
)

PAT_STICKERS = (
    "CAACAgQAAxkBAALRWV9Xs4HH0XaXfhZe-jWaZoXfs-IsAAJYAwACdDgSEHYOt4KvL02oGwQ",
    "CAACAgQAAxkBAALRXF9Xs6XmIeDbnoL1wiDky0TdX-CvAAKKAQAC1TMzC9A3CtiT2rqVGwQ",
)

PING_STRING = (
    "PONG!!",
    "I am here!",
)

ITEMS = (
    "cast iron skillet",
    "angry meow",
    "cricket bat",
    "wooden cane",
    "shovel",
    "toaster",
    "book",
    "laptop",
    "rubber chicken",
    "spiked bat",
    "heavy rock",
    "chunk of dirt",
    "ton of bricks",
    "rasengan",
    "spirit bomb",
    "100-Type Guanyin Bodhisattva",
    "rasenshuriken",
    "Murasame",
    "ban",
    "chunchunmaru",
    "Kubikiribōchō",
    "rasengan",
    "spherical flying kat",
)

THROW = (
    "throws",
    "flings",
    "chucks",
    "hurls",
)

HIT = (
    "hits",
    "whacks",
    "slaps",
    "smacks",
    "bashes",
    "pats",
)

EYES = [
    ["⌐■", "■"],
    [" ͠°", " °"],
    ["⇀", "↼"],
    ["´• ", " •`"],
    ["´", "`"],
    ["`", "´"],
    ["ó", "ò"],
    ["ò", "ó"],
    ["⸌", "⸍"],
    [">", "<"],
    ["Ƹ̵̡", "Ʒ"],
    ["ᗒ", "ᗕ"],
    ["⟃", "⟄"],
    ["⪧", "⪦"],
    ["⪦", "⪧"],
    ["⪩", "⪨"],
    ["⪨", "⪩"],
    ["⪰", "⪯"],
    ["⫑", "⫒"],
    ["⨴", "⨵"],
    ["⩿", "⪀"],
    ["⩾", "⩽"],
    ["⩺", "⩹"],
    ["⩹", "⩺"],
    ["◥▶", "◀◤"],
    ["◍", "◎"],
    ["/͠-", "┐͡-\\"],
    ["⌣", "⌣”"],
    [" ͡⎚", " ͡⎚"],
    ["≋"],
    ["૦ઁ"],
    ["  ͯ"],
    ["  ͌"],
    ["ළ"],
    ["◉"],
    ["☉"],
    ["・"],
    ["▰"],
    ["ᵔ"],
    [" ﾟ"],
    ["□"],
    ["☼"],
    ["*"],
    ["`"],
    ["⚆"],
    ["⊜"],
    [">"],
    ["❍"],
    ["￣"],
    ["─"],
    ["✿"],
    ["•"],
    ["T"],
    ["^"],
    ["ⱺ"],
    ["@"],
    ["ȍ"],
    ["  "],
    ["  "],
    ["x"],
    ["-"],
    ["$"],
    ["Ȍ"],
    ["ʘ"],
    ["Ꝋ"],
    [""],
    ["⸟"],
    ["๏"],
    ["ⴲ"],
    ["◕"],
    ["◔"],
    ["✧"],
    ["■"],
    ["♥"],
    [" ͡°"],
    ["¬"],
    [" º "],
    ["⨶"],
    ["⨱"],
    ["⏓"],
    ["⏒"],
    ["⍜"],
    ["⍤"],
    ["ᚖ"],
    ["ᴗ"],
    ["ಠ"],
    ["σ"],
    ["☯"],
]

MOUTHS = [
    ["v"],
    ["ᴥ"],
    ["ᗝ"],
    ["Ѡ"],
    ["ᗜ"],
    ["Ꮂ"],
    ["ᨓ"],
    ["ᨎ"],
    ["ヮ"],
    ["╭͜ʖ╮"],
    [" ͟ل͜"],
    [" ͜ʖ"],
    [" ͟ʖ"],
    [" ʖ̯"],
    ["ω"],
    [" ³"],
    [" ε "],
    ["﹏"],
    ["□"],
    ["ل͜"],
    ["‿"],
    ["╭╮"],
    ["‿‿"],
    ["▾"],
    ["‸"],
    ["Д"],
    ["∀"],
    ["!"],
    ["人"],
    ["."],
    ["ロ"],
    ["_"],
    ["෴"],
    ["ѽ"],
    ["ഌ"],
    ["⏠"],
    ["⏏"],
    ["⍊"],
    ["⍘"],
    ["ツ"],
    ["益"],
    ["╭∩╮"],
    ["Ĺ̯"],
    ["◡"],
    [" ͜つ"],
]

EARS = [
    ["q", "p"],
    ["ʢ", "ʡ"],
    ["⸮", "?"],
    ["ʕ", "ʔ"],
    ["ᖗ", "ᖘ"],
    ["ᕦ", "ᕥ"],
    ["ᕦ(", ")ᕥ"],
    ["ᕙ(", ")ᕗ"],
    ["ᘳ", "ᘰ"],
    ["ᕮ", "ᕭ"],
    ["ᕳ", "ᕲ"],
    ["(", ")"],
    ["[", "]"],
    ["¯\\_", "_/¯"],
    ["୧", "୨"],
    ["୨", "୧"],
    ["⤜(", ")⤏"],
    ["☞", "☞"],
    ["ᑫ", "ᑷ"],
    ["ᑴ", "ᑷ"],
    ["ヽ(", ")ﾉ"],
    ["\\(", ")/"],
    ["乁(", ")ㄏ"],
    ["└[", "]┘"],
    ["(づ", ")づ"],
    ["(ง", ")ง"],
    ["⎝", "⎠"],
    ["ლ(", "ლ)"],
    ["ᕕ(", ")ᕗ"],
    ["(∩", ")⊃━☆ﾟ.*"],
]

TOSS = ("Heads", "Tails")

EIGHTBALL = [
    "🟢 As I see it, yes.",
    "🟡 Ask again later.",
    "🟡 Better not tell you now.",
    "🟡 Cannot predict now.",
    "🟡 Concentrate and ask again.",
    "🟡 Don’t count on it.",
    "🟢 It is certain.",
    "🟢 It is decidedly so.",
    "🟢 Most likely.",
    "🔴 My reply is no.",
    "🔴 My sources say no.",
    "🔴 Outlook not so good.",
    "🟢 Outlook good.",
    "🟡 Reply hazy, try again.",
    "🟢 Signs point to yes.",
    "🔴 Very doubtful.",
    "🟢 Without a doubt.",
    "🟢 Yes.",
    "🟢 Yes – definitely.",
    "🟢 You may rely on it.",
]

DECIDE = ("Yes.", "No.", "Maybe.")

TABLE = (
    "(╯°□°）╯彡 ┻━┻",
    "I ran out of tables, will order more.",
    "Go do some work instead of flippin tables.",
)
